import { AttendanceRecord } from "@/src/services/attendanceService";

// 더미 출석 기록 데이터
export const mockAttendanceRecords: AttendanceRecord[] = [
  {
    id: "att_001",
    employeeId: "emp_001",
    employeeName: "홍길동",
    workDate: "2024-01-15",
    status: "PRESENT",
    scheduledStartTime: "09:00",
    scheduledEndTime: "18:00",
    actualStartTime: "09:05",
    actualEndTime: "18:10",
    totalWorkMinutes: 485,
    breakMinutes: 60,
    overtimeMinutes: 10,
    workLocation: "본사",
    checkInLatitude: 37.5665,
    checkInLongitude: 126.9780,
    notes: "정상 출근",
    isFlexible: false,
    isRemoteWork: false,
  },
  {
    id: "att_002",
    employeeId: "emp_001",
    employeeName: "홍길동",
    workDate: "2024-01-14",
    status: "LATE",
    scheduledStartTime: "09:00",
    scheduledEndTime: "18:00",
    actualStartTime: "09:25",
    actualEndTime: "18:00",
    totalWorkMinutes: 455,
    breakMinutes: 60,
    overtimeMinutes: 0,
    workLocation: "본사",
    checkInLatitude: 37.5665,
    checkInLongitude: 126.9780,
    notes: "교통 체증으로 인한 지각",
    isFlexible: false,
    isRemoteWork: false,
  },
  {
    id: "att_003",
    employeeId: "emp_001",
    employeeName: "홍길동",
    workDate: "2024-01-13",
    status: "PRESENT",
    scheduledStartTime: "09:00",
    scheduledEndTime: "18:00",
    actualStartTime: "08:55",
    actualEndTime: "19:30",
    totalWorkMinutes: 575,
    breakMinutes: 60,
    overtimeMinutes: 90,
    workLocation: "재택",
    notes: "프로젝트 마감으로 인한 야근",
    isFlexible: true,
    isRemoteWork: true,
  },
];